### ISSUE TITLE
css2(1) Bug Report

### ISSUE THREAD

**Issue by KrishBachhal** [KrishBachhal/Hire-TechGurus#17]
There are no syntax errors in the provided code, but there is a potential issue with the organization and repetition of the code. Here are some suggestions to improve it:

1. Combine the duplicate `@font-face` rules with the same `font-family`, `font-style`, and `font-weight` values. This will reduce the amount of repeated code and make it easier to maintain.

Here's an example of how to combine the first two `@font-face` rules:

```css
/* vietnamese, latin-ext */
@font-face {
  font-family: 'Barlow';
  font-style: normal;
  font-weight: 100;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/barlow/v12/7cHrv4kjgoGqM7E3b_s0wH8DnzcjTrA.woff2) format('woff2');
  unicode-range: U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB;
}

@font-face {
  font-family: 'Barlow';
  font-style: normal;
  font-weight: 100;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/barlow/v12/7cHqv4kjgoGqM7E3w-os6Vostz0rdom9.woff2) format('woff2');
  unicode-range: U+0100-02AF, U+0304, U+0308, U+0329, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
```

2. Consider using a CSS preprocessor like Sass or Less to generate the repeated `@font-face` rules automatically based on a data structure. This can save time and reduce the risk of errors.

Here's an example of how to define the `@font-face` rules using a Sass map:

```scss
$barlow-font-faces: (
  100: (
    url: "https://fonts.gstatic.com/s/barlow/v12/7cHrv4kjgoGqM7E3b_s0wH8DnzcjTrA.woff2",
    unicode-range: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0
